language: cpp
sudo: false
dist: trusty

matrix:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64
   - os: osx
     arch: amd64

addons:
    apt:
        packages:
            - cmake

stages:
    - compile
    - test

jobs:
    include:
     - stage: compile
     - script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
     - stage: test
       script: ./TestAll
